name: dv
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.13.7
  - inflect=7.0.0
  - jupyter=1.1.1
  - matplotlib=3.10.0
  - networkx=3.4.2
  - numpy=2.3.1
  - pandas=2.3.1
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - seaborn=0.13.2
  - statsmodels=0.14.5